describe('atom namespace', () => {
  describe('workspace', () => {
    it('should define all properties', () => {
      expect(atom.workspace.addModalPanel).toBeDefined();
    });
  });
  it('should define all properties', () => {
    // expect(atom.blobStore).toBeDefined();
    // expect(atom.applicationDelegate).toBeDefined();
    // expect(atom.window).toBeDefined();
    // expect(atom.document).toBeDefined();
    // expect(atom.configDirPath).toBeDefined();
    // expect(atom.enablePersistence).toBeDefined();
    // expect(atom.unloaded).toBeDefined();
    // expect(atom.loadTime).toBeDefined();
    // expect(atom.emitter).toBeDefined();
    // expect(atom.disposables).toBeDefined();
    // expect(atom.stateStore).toBeDefined();
    // expect(atom.deserializers).toBeDefined();
    // expect(atom.deserializeTimings).toBeDefined();
    expect(atom.views).toBeDefined();
    expect(atom.notifications).toBeDefined();
    expect(atom.config).toBeDefined();
    expect(atom.keymaps).toBeDefined();
    expect(atom.tooltips).toBeDefined();
    expect(atom.commands).toBeDefined();
    expect(atom.grammars).toBeDefined();
    expect(atom.styles).toBeDefined();
    expect(atom.packages).toBeDefined();
    expect(atom.themes).toBeDefined();
    expect(atom.menu).toBeDefined();
    expect(atom.contextMenu).toBeDefined();
    expect(atom.clipboard).toBeDefined();
    expect(atom.project).toBeDefined();
    // expect(atom.appVersion).toBeDefined();
    // expect(atom.commandInstaller).toBeDefined();
    expect(atom.workspace).toBeDefined();
    // expect(atom.textEditors).toBeDefined();
    // expect(atom.autoUpdater).toBeDefined();
    // expect(atom.initialStyleElements).toBeDefined();
    // expect(atom.stylesElement).toBeDefined();
    // expect(atom.previousWindowErrorHandler).toBeDefined();
    // expect(atom.windowEventHandler).toBeDefined();
    expect(atom.constructor).toBeDefined();
    // expect(atom.lastUncaughtError).toBeDefined();
    // expect(atom.saveStateDebounceInterval).toBeDefined();
    // expect(atom.attachSaveStateListeners).toBeDefined();
    // expect(atom.setConfigSchema).toBeDefined();
    // expect(atom.registerDefaultDeserializers).toBeDefined();
    // expect(atom.registerDefaultCommands).toBeDefined();
    // expect(atom.registerDefaultViewProviders).toBeDefined();
    // expect(atom.registerDefaultOpeners).toBeDefined();
    // expect(atom.registerDefaultTargetForKeymaps).toBeDefined();
    // expect(atom.observeAutoHideMenuBar).toBeDefined();
    // expect(atom.reset).toBeDefined();
    // expect(atom.destroy).toBeDefined();
    expect(atom.onDidBeep).toBeDefined();
    expect(atom.onWillThrowError).toBeDefined();
    expect(atom.onDidThrowError).toBeDefined();
    // expect(atom.onDidFailAssertion).toBeDefined();
    expect(atom.inDevMode).toBeDefined();
    expect(atom.inSafeMode).toBeDefined();
    expect(atom.inSpecMode).toBeDefined();
    // expect(atom.isFirstLoad).toBeDefined();
    expect(atom.getVersion).toBeDefined();
    // expect(atom.getReleaseChannel).toBeDefined();
    expect(atom.isReleasedVersion).toBeDefined();
    expect(atom.getWindowLoadTime).toBeDefined();
    expect(atom.getLoadSettings).toBeDefined();
    expect(atom.open).toBeDefined();
    expect(atom.pickFolder).toBeDefined();
    expect(atom.close).toBeDefined();
    expect(atom.getSize).toBeDefined();
    expect(atom.setSize).toBeDefined();
    expect(atom.getPosition).toBeDefined();
    expect(atom.setPosition).toBeDefined();
    expect(atom.getCurrentWindow).toBeDefined();
    expect(atom.center).toBeDefined();
    expect(atom.focus).toBeDefined();
    expect(atom.show).toBeDefined();
    expect(atom.hide).toBeDefined();
    expect(atom.reload).toBeDefined();
    expect(atom.isMaximized).toBeDefined();
    // expect(atom.maximize).toBeDefined();
    expect(atom.isFullScreen).toBeDefined();
    expect(atom.setFullScreen).toBeDefined();
    expect(atom.toggleFullScreen).toBeDefined();
    // expect(atom.displayWindow).toBeDefined();
    // expect(atom.getWindowDimensions).toBeDefined();
    // expect(atom.setWindowDimensions).toBeDefined();
    // expect(atom.isValidDimensions).toBeDefined();
    // expect(atom.storeWindowDimensions).toBeDefined();
    // expect(atom.getDefaultWindowDimensions).toBeDefined();
    // expect(atom.restoreWindowDimensions).toBeDefined();
    // expect(atom.restoreWindowBackground).toBeDefined();
    // expect(atom.storeWindowBackground).toBeDefined();
    // expect(atom.startEditorWindow).toBeDefined();
    // expect(atom.serialize).toBeDefined();
    // expect(atom.unloadEditorWindow).toBeDefined();
    // expect(atom.openInitialEmptyEditorIfNecessary).toBeDefined();
    // expect(atom.installUncaughtErrorHandler).toBeDefined();
    // expect(atom.uninstallUncaughtErrorHandler).toBeDefined();
    // expect(atom.installWindowEventHandler).toBeDefined();
    // expect(atom.uninstallWindowEventHandler).toBeDefined();
    expect(atom.beep).toBeDefined();
    expect(atom.confirm).toBeDefined();
    expect(atom.openDevTools).toBeDefined();
    expect(atom.toggleDevTools).toBeDefined();
    expect(atom.executeJavaScriptInDevTools).toBeDefined();
    // expect(atom.assert).toBeDefined();
    // expect(atom.loadThemes).toBeDefined();
    // expect(atom.watchProjectPaths).toBeDefined();
    // expect(atom.setDocumentEdited).toBeDefined();
    // expect(atom.setRepresentedFilename).toBeDefined();
    // expect(atom.addProjectFolder).toBeDefined();
    // expect(atom.showSaveDialog).toBeDefined();
    // expect(atom.showSaveDialogSync).toBeDefined();
    // expect(atom.saveBlobStoreSync).toBeDefined();
    // expect(atom.saveState).toBeDefined();
    // expect(atom.loadState).toBeDefined();
    // expect(atom.deserialize).toBeDefined();
    // expect(atom.getStateKey).toBeDefined();
    // expect(atom.getStorageFolder).toBeDefined();
    // expect(atom.getConfigDirPath).toBeDefined();
    // expect(atom.getUserInitScriptPath).toBeDefined();
    // expect(atom.requireUserInitScript).toBeDefined();
    // expect(atom.onUpdateAvailable).toBeDefined();
    // expect(atom.updateAvailable).toBeDefined();
    // expect(atom.listenForUpdates).toBeDefined();
    // expect(atom.setBodyPlatformClass).toBeDefined();
    // expect(atom.setAutoHideMenuBar).toBeDefined();
    // expect(atom.dispatchApplicationMenuCommand).toBeDefined();
    // expect(atom.dispatchContextMenuCommand).toBeDefined();
    // expect(atom.openLocations).toBeDefined();
    // expect(atom.alive).toBeDefined();
    // expect(atom.assignId).toBeDefined();
    // expect(atom.isAlive).toBeDefined();
    // expect(atom.isDestroyed).toBeDefined();
  });
});
